# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Agile Engineering"
email: "contact@agile.engineering"
description: "Everything You Always Wanted to Know About Agile Engineering - But Were Afraid to Ask"
baseurl: "/spanish_orange"
url: "http://improuv.github.io"
permalink: "/blog/:title"
#googleAnalyticsTrackingId: "UA-43643469-5"
#googleAnalyticsSiteUrl: "improuv.github.io"
#siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "improuv GmbH"
organizerAlternateName: "improuv GmbH"
organizerDescription: "Coaching & Training Company focused on Lean & Agile. Based in Munich & Hamburg."
organizerEmail: "training@improuv.com"
organizerLogo: "/img/logos/improuv_logo_negschwarz.jpg"
organizerLink: "http://www.improuv.com/"

# Head
metaKeywords: "agile, scrum, development, tdd, bdd, programming, pair programming, extreme programming, java, ruby, android, groovy, improuv, kanban"
twitterAccount: "@improuv"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/logos/improuv_logo_weiss.png"

# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/articles/", text: "Articles"}
 - {permalink: "/trainings/", text: "Trainings"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
# - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
# - {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "About <typeout> Engineering"
eventDate: "What's next in 2015"
typeoutTextValues: '"", "Next Generation", "Agile", "Lean"'
typeoutFallback: "Agile"
heroButtons:
 - {link: "http://improuv.com", text: "Book now"}
# - {permalink: "/#tickets", text: "Buy tickets"}

# About Block
aboutTitle: "About Agile Engineering"
aboutBlock:
 - {title: "Articles", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Blogs", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Trainings", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Latest News Block
latestNewsTitle: "Latest news"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "improuv GmbH"
eventLocationLink: "http://improuv.com"
eventStreetAddress: "Brecherspitzstr. 8"
eventAddressLocality: "Munich"
eventAddressLocalityRegion: "Bavaria"
eventPostalCode: "81541"
eventAddressCountry: "Germany"
eventStartTime: "2015-01-01T00:00"
eventDoorTime: "09:00"
eventEndTime: "2100-12-31T23:59"
eventPlaceCoordinates: "48.115884,11.589546"
mapCenterCoordinates: "48.115884,11.589546"
mapMobileCenterCoordinates: "48.115884,11.589546"

# Tweets Feed Block
#tweetsFeedImage: "twitter-feed.jpg"
#tweetsFeedTitle: "What's Up?"
#twitterHashTag: "agile.engineering"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=improuv", icon: "twitter"}
 - {link: "https://facebook.com/improuv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.improuv.com", text: "www.improuv.com"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:training@improuv.com", text: "training@improuv.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "improuv-csd"

# Team Block
teamBlockTitle: "About us"
aboutUs: "We help you deliver reliable high quality software more efficiently. <br>Agile software development places high demands on every team member. Good software development skills alone are not enough. For your teams to regularly deliver high quality software they will need to develop good agile software engineering skills. <br>We will support you in the efficient delivery of high quality reliable software. We coach your developers and testers and provide best practices and support in Continuous Delivery, Test-Driven-Development, Clean Code, Refactoring and Pair Programming, and support your teams and projects with experienced agile developers. <br><br>Our improuv trainer team for technical courses. They have a deep understanding in agile engineering topics like test driven development (TDD), clean code or continuous integration (CI). During their work as agile coaches and team members in several teams they gained a lot of practical experiences. They like to share their knowledge."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "48.115884,11.589546"
logisticsMapMobileCenterCoordinates: "48.115884,11.589546"

